# Generated by Django 4.1.6 on 2023-05-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorsMastertable',
        ),
        migrations.DeleteModel(
            name='TimeSlottable',
        ),
    ]
