# Generated by Django 4.1.6 on 2023-07-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='patient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='patient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='patient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patientschedule',
            old_name='patient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patientsummary',
            old_name='patient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='patient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='grabdocuser',
            name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='grabdocuser',
            name='patient_last_name',
        ),
        migrations.AlterField(
            model_name='grabdocuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grabdocuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('user', 'first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('user', 'family_member', 'file_name')},
        ),
        migrations.AlterUniqueTogether(
            name='patientschedule',
            unique_together={('doctors_schedule', 'user')},
        ),
    ]
