# Generated by Django 4.1.6 on 2023-05-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_delete_doctorsmastertable_delete_timeslottable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('online', models.BooleanField()),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('about_doctor', models.TextField(blank=True, null=True)),
                ('specality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.specalitymastertable')),
            ],
        ),
    ]
