# Generated by Django 4.1.6 on 2023-07-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_rename_patient_familymember_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now_add=True)),
                ('login_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Pay on Visit', 'pay on Visit'), ('Amazon Pay', 'Amazon Pay'), ('Card', 'Card'), ('PayPal', 'PayPal'), ('Skrill', 'Skrill')], max_length=12)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now_add=True)),
                ('patient_schedule', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='patient_app.patientschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
