# Generated by Django 4.1.6 on 2023-05-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateTimeField(null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.doctors')),
            ],
        ),
    ]
