# Generated by Django 4.1.6 on 2023-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_remove_patientmastertable_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmastertable',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmastertable',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
