# Generated by Django 4.1.6 on 2023-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_userdevice_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientschedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20),
            preserve_default=False,
        ),
    ]
