# Generated by Django 4.1.6 on 2023-03-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_remove_patientmastertable_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantDiseaseTable',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('disease_type', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'consultant_disease_table',
            },
        ),
        migrations.CreateModel(
            name='SpecalityMastertable',
            fields=[
                ('specality_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('specality_name', models.CharField(blank=True, max_length=200, null=True)),
                ('specality_description', models.CharField(blank=True, max_length=400, null=True)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.consultantdiseasetable')),
            ],
            options={
                'db_table': 'specality_master_table',
            },
        ),
        migrations.CreateModel(
            name='DoctorsMastertable',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.FloatField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('specality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.specalitymastertable')),
            ],
            options={
                'db_table': 'doctors_master_table',
            },
        ),
    ]
