# Generated by Django 4.1.6 on 2023-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_rename_doctor_id_doctorsschedule_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmastertable',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientmastertable',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmastertable',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
