# Generated by Django 4.1.6 on 2023-05-22 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0006_patientmastertable_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSummary',
            fields=[
                ('summary', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
