# Generated by Django 4.1.6 on 2023-04-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0007_mobile_reg_timeslottable_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile_Reg',
        ),
    ]
