# Generated by Django 4.1.6 on 2023-05-23 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0007_patientsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.doctorsschedule')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
