# Generated by Django 4.1.6 on 2023-04-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0009_mobile_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_reg',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobile_reg',
            name='number_of_attements',
            field=models.IntegerField(default=0),
        ),
    ]
