# Generated by Django 4.1.6 on 2023-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0009_alter_patientschedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('Dad', 'Dad'), ('Mom', 'MOm'), ('husband', 'Husband'), ('Wife', 'Wife'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Others', 'Others')], max_length=10)),
            ],
        ),
    ]
