# Generated by Django 4.1.6 on 2023-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0010_mobile_reg_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_reg',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
