# Generated by Django 4.1.6 on 2023-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0011_alter_mobile_reg_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_reg',
            name='otp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
