# Generated by Django 4.1.6 on 2023-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0012_alter_familymember_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
