# Generated by Django 4.1.6 on 2023-05-26 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0013_alter_familymember_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=50)),
                ('upload_record', models.CharField(blank=True, max_length=50, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.familymember')),
            ],
        ),
    ]
