# Generated by Django 4.1.6 on 2023-05-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0014_medicalrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='record_for',
            new_name='family_member',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='upload_record',
            new_name='file_name',
        ),
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('patient', 'family_member', 'file_name')},
        ),
    ]
