# Generated by Django 4.1.6 on 2023-05-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0015_rename_record_for_medicalrecord_family_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientScheduleMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.medicalrecord')),
                ('patient_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patientschedule')),
            ],
        ),
    ]
