# Generated by Django 4.1.6 on 2023-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0017_alter_patientschedulemedicalrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='fee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
