# Generated by Django 4.1.6 on 2023-06-20 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0019_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 6, 20, 22, 23, 41, 71728)),
            preserve_default=False,
        ),
    ]
