# Generated by Django 4.1.6 on 2023-06-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0020_alter_reviews_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_doctor', to='patient_app.doctors'),
        ),
    ]
